- .gitignore
- config/config.js
- controllers/testController.mjs
- index.mjs
- models/index.mjs
- package-lock.json
- package.json
- routes.mjs
https://lee-kimmixq.atlassian.net/browse/MC-24?atlOrigin=eyJpIjoiMTFjMWE5OGI0YzRjNDllMTgzMDZjYTIzMGQyMTQ2ZTgiLCJwIjoiaiJ9
> MC-24 - completed initial setup for packages and folders

- .gitignore
- README.md
- config/config.js
- index.mjs
- package-lock.json
- package.json
https://lee-kimmixq.atlassian.net/browse/MC-22?atlOrigin=eyJpIjoiMDBhYzBiYTFhMzE5NGRmZDkxZWE1NTYyODc5ODY1NTciLCJwIjoiaiJ9
> MC-22 - added dotenv setup

- config/config.js
https://lee-kimmixq.atlassian.net/browse/MC-17?atlOrigin=eyJpIjoiMWU4NGE5MTYyMmRmNDIyMThmMzkyNDA0NTk1MGExYTMiLCJwIjoiaiJ9
> MC-17 - set up sequelize config

- migrations/20220628124951-create-categories-table.js
https://lee-kimmixq.atlassian.net/browse/MC-28
> MC-28 fixed case for isincome in categories migration

- migrations/20220628125918-create-transaction-categories-table.js
https://lee-kimmixq.atlassian.net/browse/MC-29
> MC-29 fixed column header for transaction_id

- models/category.mjs
- models/index.mjs
- models/transaction.mjs
- models/user.mjs
https://lee-kimmixq.atlassian.net/browse/MC-19
> MC-19 create models

- migrations/20220628124410-create-users-table.js
- package-lock.json
- package.json
- seeders/20220629115735-seed-users-data.js
- seeders/20220629125727-seed-categories-table.js
- seeders/20220629131004-seed-transactions-table.js
- utils/getHash.js
https://lee-kimmixq.atlassian.net/browse/MC-20
> MC-20 created seed data for all tables and rectified migrations

- authentication/passport.mjs
- controllers/users.mjs
- index.mjs
- package-lock.json
- package.json
- routes.mjs
- utils/extractCookie.js
- utils/getHash.js
https://lee-kimmixq.atlassian.net/browse/MC-23
> MC-23 create login route and controller and setup passportjs with jwt

- controllers/users.mjs
- routes.mjs
https://lee-kimmixq.atlassian.net/browse/MC-37
> MC-37 created logout route and controller function

- controllers/transactions.mjs
https://lee-kimmixq.atlassian.net/browse/MC-39
> MC-39 amended index method of transaction controller to accept query params

- controllers/transactions.mjs
https://lee-kimmixq.atlassian.net/browse/MC-42
> MC-42 amended index method in transaction controller to filter by isIncome

- controllers/transactions.mjs
- routes.mjs
https://lee-kimmixq.atlassian.net/browse/MC-38
> MC-38 created route and controller to get total amounts

- controllers/transactions.mjs
https://lee-kimmixq.atlassian.net/browse/MC-40
> MC-40 amend get all transactions endpoint to filter by category and min/max amount

- controllers/users.mjs
- routes.mjs
https://lee-kimmixq.atlassian.net/browse/MC-43
> MC-43 created route and controller to get user details

- controllers/transactions.mjs
https://lee-kimmixq.atlassian.net/browse/MC-48
> MC-48 amended calcTotal function to allow isIncome query param

- seeders/20220629131004-seed-transactions-table.js
- seeders/20220704171057-seed-transactions-table-for-july.js
https://lee-kimmixq.atlassian.net/browse/MC-62
> MC-62 created seed data for july for mock user 1

- controllers/transactions.mjs
https://lee-kimmixq.atlassian.net/browse/MC-67
> MC-67 fixed min max query error in transactions controller

- utils/getBreakdown.js
https://lee-kimmixq.atlassian.net/browse/MC-102
> updated data strcture of transaction breakdown into categories

- controllers/transactions.mjs
- utils/getTxnQueryOptions.js
- utils/getTxnResBody.js
https://lee-kimmixq.atlassian.net/browse/MC-99
> MC099 refactored transactions controller

- controllers/transactions.mjs
- routers/transactionRouter.mjs
https://lee-kimmixq.atlassian.net/browse/MC-112
> MC-112 created route and controller for reports bar chart

- migrations/20220713114043-create-budgets-table.js
- models/budgets.mjs
- models/index.mjs
- seeders/20220713114850-seed-budgets-table.js
https://lee-kimmixq.atlassian.net/browse/MC-118
> MC-118 created budgets table in db

- controllers/transactions.mjs
- routers/transactionRouter.mjs
- utils/getTxnQueryOptions.js
https://lee-kimmixq.atlassian.net/browse/MC-122
> MC-122 amended update function txn controller

- config/nodemailer.config.js
https://lee-kimmixq.atlassian.net/browse/MC-130
> MC-130: Update styling of email and page components

- controllers/budgets.mjs
https://lee-kimmixq.atlassian.net/browse/MC-132
> MC-132 added query for current total in budgets index

- seeders/20220721183036-seed-data-for-presentation.js
https://lee-kimmixq.atlassian.net/browse/MC-143
> MC-143 seeded mock data for presentation use

- controllers/users.mjs
- routers/userRouter.mjs
https://lee-kimmixq.atlassian.net/browse/MC-155
> MC-155 make user name on account page dynamic
